// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packet.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_packet_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_packet_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_packet_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_packet_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_packet_2eproto;
namespace ProtoMessage {
class Packet;
struct PacketDefaultTypeInternal;
extern PacketDefaultTypeInternal _Packet_default_instance_;
class PacketHeader;
struct PacketHeaderDefaultTypeInternal;
extern PacketHeaderDefaultTypeInternal _PacketHeader_default_instance_;
class PacketHeader_IdStringEntry;
struct PacketHeader_IdStringEntryDefaultTypeInternal;
extern PacketHeader_IdStringEntryDefaultTypeInternal _PacketHeader_IdStringEntry_default_instance_;
}  // namespace ProtoMessage
PROTOBUF_NAMESPACE_OPEN
template<> ::ProtoMessage::Packet* Arena::CreateMaybeMessage<::ProtoMessage::Packet>(Arena*);
template<> ::ProtoMessage::PacketHeader* Arena::CreateMaybeMessage<::ProtoMessage::PacketHeader>(Arena*);
template<> ::ProtoMessage::PacketHeader_IdStringEntry* Arena::CreateMaybeMessage<::ProtoMessage::PacketHeader_IdStringEntry>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace ProtoMessage {

// ===================================================================

class PacketHeader_IdStringEntry final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ProtoMessage.PacketHeader.IdStringEntry) */ {
 public:
  inline PacketHeader_IdStringEntry() : PacketHeader_IdStringEntry(nullptr) {}
  ~PacketHeader_IdStringEntry() override;
  explicit PROTOBUF_CONSTEXPR PacketHeader_IdStringEntry(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PacketHeader_IdStringEntry(const PacketHeader_IdStringEntry& from);
  PacketHeader_IdStringEntry(PacketHeader_IdStringEntry&& from) noexcept
    : PacketHeader_IdStringEntry() {
    *this = ::std::move(from);
  }

  inline PacketHeader_IdStringEntry& operator=(const PacketHeader_IdStringEntry& from) {
    CopyFrom(from);
    return *this;
  }
  inline PacketHeader_IdStringEntry& operator=(PacketHeader_IdStringEntry&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PacketHeader_IdStringEntry& default_instance() {
    return *internal_default_instance();
  }
  static inline const PacketHeader_IdStringEntry* internal_default_instance() {
    return reinterpret_cast<const PacketHeader_IdStringEntry*>(
               &_PacketHeader_IdStringEntry_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PacketHeader_IdStringEntry& a, PacketHeader_IdStringEntry& b) {
    a.Swap(&b);
  }
  inline void Swap(PacketHeader_IdStringEntry* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PacketHeader_IdStringEntry* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PacketHeader_IdStringEntry* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PacketHeader_IdStringEntry>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PacketHeader_IdStringEntry& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PacketHeader_IdStringEntry& from) {
    PacketHeader_IdStringEntry::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PacketHeader_IdStringEntry* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ProtoMessage.PacketHeader.IdStringEntry";
  }
  protected:
  explicit PacketHeader_IdStringEntry(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kValueFieldNumber = 2,
    kKeyFieldNumber = 1,
  };
  // optional string value = 2;
  bool has_value() const;
  private:
  bool _internal_has_value() const;
  public:
  void clear_value();
  const std::string& value() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_value(ArgT0&& arg0, ArgT... args);
  std::string* mutable_value();
  PROTOBUF_NODISCARD std::string* release_value();
  void set_allocated_value(std::string* value);
  private:
  const std::string& _internal_value() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_value(const std::string& value);
  std::string* _internal_mutable_value();
  public:

  // optional uint32 key = 1;
  bool has_key() const;
  private:
  bool _internal_has_key() const;
  public:
  void clear_key();
  uint32_t key() const;
  void set_key(uint32_t value);
  private:
  uint32_t _internal_key() const;
  void _internal_set_key(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:ProtoMessage.PacketHeader.IdStringEntry)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr value_;
    uint32_t key_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_packet_2eproto;
};
// -------------------------------------------------------------------

class PacketHeader final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ProtoMessage.PacketHeader) */ {
 public:
  inline PacketHeader() : PacketHeader(nullptr) {}
  ~PacketHeader() override;
  explicit PROTOBUF_CONSTEXPR PacketHeader(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PacketHeader(const PacketHeader& from);
  PacketHeader(PacketHeader&& from) noexcept
    : PacketHeader() {
    *this = ::std::move(from);
  }

  inline PacketHeader& operator=(const PacketHeader& from) {
    CopyFrom(from);
    return *this;
  }
  inline PacketHeader& operator=(PacketHeader&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PacketHeader& default_instance() {
    return *internal_default_instance();
  }
  static inline const PacketHeader* internal_default_instance() {
    return reinterpret_cast<const PacketHeader*>(
               &_PacketHeader_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(PacketHeader& a, PacketHeader& b) {
    a.Swap(&b);
  }
  inline void Swap(PacketHeader* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PacketHeader* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PacketHeader* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PacketHeader>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PacketHeader& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PacketHeader& from) {
    PacketHeader::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PacketHeader* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ProtoMessage.PacketHeader";
  }
  protected:
  explicit PacketHeader(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef PacketHeader_IdStringEntry IdStringEntry;

  // accessors -------------------------------------------------------

  enum : int {
    kIdStringsFieldNumber = 4,
    kObjIdFieldNumber = 1,
    kTickFreqFieldNumber = 3,
    kVerFieldNumber = 2,
  };
  // repeated .ProtoMessage.PacketHeader.IdStringEntry id_strings = 4;
  int id_strings_size() const;
  private:
  int _internal_id_strings_size() const;
  public:
  void clear_id_strings();
  ::ProtoMessage::PacketHeader_IdStringEntry* mutable_id_strings(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ProtoMessage::PacketHeader_IdStringEntry >*
      mutable_id_strings();
  private:
  const ::ProtoMessage::PacketHeader_IdStringEntry& _internal_id_strings(int index) const;
  ::ProtoMessage::PacketHeader_IdStringEntry* _internal_add_id_strings();
  public:
  const ::ProtoMessage::PacketHeader_IdStringEntry& id_strings(int index) const;
  ::ProtoMessage::PacketHeader_IdStringEntry* add_id_strings();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ProtoMessage::PacketHeader_IdStringEntry >&
      id_strings() const;

  // required string obj_id = 1;
  bool has_obj_id() const;
  private:
  bool _internal_has_obj_id() const;
  public:
  void clear_obj_id();
  const std::string& obj_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_obj_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_obj_id();
  PROTOBUF_NODISCARD std::string* release_obj_id();
  void set_allocated_obj_id(std::string* obj_id);
  private:
  const std::string& _internal_obj_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_obj_id(const std::string& value);
  std::string* _internal_mutable_obj_id();
  public:

  // required uint64 tick_freq = 3;
  bool has_tick_freq() const;
  private:
  bool _internal_has_tick_freq() const;
  public:
  void clear_tick_freq();
  uint64_t tick_freq() const;
  void set_tick_freq(uint64_t value);
  private:
  uint64_t _internal_tick_freq() const;
  void _internal_set_tick_freq(uint64_t value);
  public:

  // optional uint32 ver = 2 [default = 0];
  bool has_ver() const;
  private:
  bool _internal_has_ver() const;
  public:
  void clear_ver();
  uint32_t ver() const;
  void set_ver(uint32_t value);
  private:
  uint32_t _internal_ver() const;
  void _internal_set_ver(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:ProtoMessage.PacketHeader)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ProtoMessage::PacketHeader_IdStringEntry > id_strings_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr obj_id_;
    uint64_t tick_freq_;
    uint32_t ver_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_packet_2eproto;
};
// -------------------------------------------------------------------

class Packet final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ProtoMessage.Packet) */ {
 public:
  inline Packet() : Packet(nullptr) {}
  ~Packet() override;
  explicit PROTOBUF_CONSTEXPR Packet(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Packet(const Packet& from);
  Packet(Packet&& from) noexcept
    : Packet() {
    *this = ::std::move(from);
  }

  inline Packet& operator=(const Packet& from) {
    CopyFrom(from);
    return *this;
  }
  inline Packet& operator=(Packet&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Packet& default_instance() {
    return *internal_default_instance();
  }
  static inline const Packet* internal_default_instance() {
    return reinterpret_cast<const Packet*>(
               &_Packet_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Packet& a, Packet& b) {
    a.Swap(&b);
  }
  inline void Swap(Packet* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Packet* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Packet* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Packet>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Packet& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Packet& from) {
    Packet::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Packet* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ProtoMessage.Packet";
  }
  protected:
  explicit Packet(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTickFieldNumber = 1,
    kAddrFieldNumber = 3,
    kCmdFieldNumber = 2,
    kSizeFieldNumber = 4,
    kPktIdFieldNumber = 6,
    kPcFieldNumber = 7,
    kFlagsFieldNumber = 5,
  };
  // required uint64 tick = 1;
  bool has_tick() const;
  private:
  bool _internal_has_tick() const;
  public:
  void clear_tick();
  uint64_t tick() const;
  void set_tick(uint64_t value);
  private:
  uint64_t _internal_tick() const;
  void _internal_set_tick(uint64_t value);
  public:

  // required uint64 addr = 3;
  bool has_addr() const;
  private:
  bool _internal_has_addr() const;
  public:
  void clear_addr();
  uint64_t addr() const;
  void set_addr(uint64_t value);
  private:
  uint64_t _internal_addr() const;
  void _internal_set_addr(uint64_t value);
  public:

  // required uint32 cmd = 2;
  bool has_cmd() const;
  private:
  bool _internal_has_cmd() const;
  public:
  void clear_cmd();
  uint32_t cmd() const;
  void set_cmd(uint32_t value);
  private:
  uint32_t _internal_cmd() const;
  void _internal_set_cmd(uint32_t value);
  public:

  // required uint32 size = 4;
  bool has_size() const;
  private:
  bool _internal_has_size() const;
  public:
  void clear_size();
  uint32_t size() const;
  void set_size(uint32_t value);
  private:
  uint32_t _internal_size() const;
  void _internal_set_size(uint32_t value);
  public:

  // optional uint64 pkt_id = 6;
  bool has_pkt_id() const;
  private:
  bool _internal_has_pkt_id() const;
  public:
  void clear_pkt_id();
  uint64_t pkt_id() const;
  void set_pkt_id(uint64_t value);
  private:
  uint64_t _internal_pkt_id() const;
  void _internal_set_pkt_id(uint64_t value);
  public:

  // optional uint64 pc = 7;
  bool has_pc() const;
  private:
  bool _internal_has_pc() const;
  public:
  void clear_pc();
  uint64_t pc() const;
  void set_pc(uint64_t value);
  private:
  uint64_t _internal_pc() const;
  void _internal_set_pc(uint64_t value);
  public:

  // optional uint32 flags = 5;
  bool has_flags() const;
  private:
  bool _internal_has_flags() const;
  public:
  void clear_flags();
  uint32_t flags() const;
  void set_flags(uint32_t value);
  private:
  uint32_t _internal_flags() const;
  void _internal_set_flags(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:ProtoMessage.Packet)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint64_t tick_;
    uint64_t addr_;
    uint32_t cmd_;
    uint32_t size_;
    uint64_t pkt_id_;
    uint64_t pc_;
    uint32_t flags_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_packet_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PacketHeader_IdStringEntry

// optional uint32 key = 1;
inline bool PacketHeader_IdStringEntry::_internal_has_key() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool PacketHeader_IdStringEntry::has_key() const {
  return _internal_has_key();
}
inline void PacketHeader_IdStringEntry::clear_key() {
  _impl_.key_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline uint32_t PacketHeader_IdStringEntry::_internal_key() const {
  return _impl_.key_;
}
inline uint32_t PacketHeader_IdStringEntry::key() const {
  // @@protoc_insertion_point(field_get:ProtoMessage.PacketHeader.IdStringEntry.key)
  return _internal_key();
}
inline void PacketHeader_IdStringEntry::_internal_set_key(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.key_ = value;
}
inline void PacketHeader_IdStringEntry::set_key(uint32_t value) {
  _internal_set_key(value);
  // @@protoc_insertion_point(field_set:ProtoMessage.PacketHeader.IdStringEntry.key)
}

// optional string value = 2;
inline bool PacketHeader_IdStringEntry::_internal_has_value() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool PacketHeader_IdStringEntry::has_value() const {
  return _internal_has_value();
}
inline void PacketHeader_IdStringEntry::clear_value() {
  _impl_.value_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& PacketHeader_IdStringEntry::value() const {
  // @@protoc_insertion_point(field_get:ProtoMessage.PacketHeader.IdStringEntry.value)
  return _internal_value();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PacketHeader_IdStringEntry::set_value(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000001u;
 _impl_.value_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ProtoMessage.PacketHeader.IdStringEntry.value)
}
inline std::string* PacketHeader_IdStringEntry::mutable_value() {
  std::string* _s = _internal_mutable_value();
  // @@protoc_insertion_point(field_mutable:ProtoMessage.PacketHeader.IdStringEntry.value)
  return _s;
}
inline const std::string& PacketHeader_IdStringEntry::_internal_value() const {
  return _impl_.value_.Get();
}
inline void PacketHeader_IdStringEntry::_internal_set_value(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.value_.Set(value, GetArenaForAllocation());
}
inline std::string* PacketHeader_IdStringEntry::_internal_mutable_value() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.value_.Mutable(GetArenaForAllocation());
}
inline std::string* PacketHeader_IdStringEntry::release_value() {
  // @@protoc_insertion_point(field_release:ProtoMessage.PacketHeader.IdStringEntry.value)
  if (!_internal_has_value()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* p = _impl_.value_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.value_.IsDefault()) {
    _impl_.value_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void PacketHeader_IdStringEntry::set_allocated_value(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.value_.SetAllocated(value, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.value_.IsDefault()) {
    _impl_.value_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ProtoMessage.PacketHeader.IdStringEntry.value)
}

// -------------------------------------------------------------------

// PacketHeader

// required string obj_id = 1;
inline bool PacketHeader::_internal_has_obj_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool PacketHeader::has_obj_id() const {
  return _internal_has_obj_id();
}
inline void PacketHeader::clear_obj_id() {
  _impl_.obj_id_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& PacketHeader::obj_id() const {
  // @@protoc_insertion_point(field_get:ProtoMessage.PacketHeader.obj_id)
  return _internal_obj_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PacketHeader::set_obj_id(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000001u;
 _impl_.obj_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ProtoMessage.PacketHeader.obj_id)
}
inline std::string* PacketHeader::mutable_obj_id() {
  std::string* _s = _internal_mutable_obj_id();
  // @@protoc_insertion_point(field_mutable:ProtoMessage.PacketHeader.obj_id)
  return _s;
}
inline const std::string& PacketHeader::_internal_obj_id() const {
  return _impl_.obj_id_.Get();
}
inline void PacketHeader::_internal_set_obj_id(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.obj_id_.Set(value, GetArenaForAllocation());
}
inline std::string* PacketHeader::_internal_mutable_obj_id() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.obj_id_.Mutable(GetArenaForAllocation());
}
inline std::string* PacketHeader::release_obj_id() {
  // @@protoc_insertion_point(field_release:ProtoMessage.PacketHeader.obj_id)
  if (!_internal_has_obj_id()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* p = _impl_.obj_id_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.obj_id_.IsDefault()) {
    _impl_.obj_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void PacketHeader::set_allocated_obj_id(std::string* obj_id) {
  if (obj_id != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.obj_id_.SetAllocated(obj_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.obj_id_.IsDefault()) {
    _impl_.obj_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ProtoMessage.PacketHeader.obj_id)
}

// optional uint32 ver = 2 [default = 0];
inline bool PacketHeader::_internal_has_ver() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool PacketHeader::has_ver() const {
  return _internal_has_ver();
}
inline void PacketHeader::clear_ver() {
  _impl_.ver_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline uint32_t PacketHeader::_internal_ver() const {
  return _impl_.ver_;
}
inline uint32_t PacketHeader::ver() const {
  // @@protoc_insertion_point(field_get:ProtoMessage.PacketHeader.ver)
  return _internal_ver();
}
inline void PacketHeader::_internal_set_ver(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.ver_ = value;
}
inline void PacketHeader::set_ver(uint32_t value) {
  _internal_set_ver(value);
  // @@protoc_insertion_point(field_set:ProtoMessage.PacketHeader.ver)
}

// required uint64 tick_freq = 3;
inline bool PacketHeader::_internal_has_tick_freq() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool PacketHeader::has_tick_freq() const {
  return _internal_has_tick_freq();
}
inline void PacketHeader::clear_tick_freq() {
  _impl_.tick_freq_ = uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline uint64_t PacketHeader::_internal_tick_freq() const {
  return _impl_.tick_freq_;
}
inline uint64_t PacketHeader::tick_freq() const {
  // @@protoc_insertion_point(field_get:ProtoMessage.PacketHeader.tick_freq)
  return _internal_tick_freq();
}
inline void PacketHeader::_internal_set_tick_freq(uint64_t value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.tick_freq_ = value;
}
inline void PacketHeader::set_tick_freq(uint64_t value) {
  _internal_set_tick_freq(value);
  // @@protoc_insertion_point(field_set:ProtoMessage.PacketHeader.tick_freq)
}

// repeated .ProtoMessage.PacketHeader.IdStringEntry id_strings = 4;
inline int PacketHeader::_internal_id_strings_size() const {
  return _impl_.id_strings_.size();
}
inline int PacketHeader::id_strings_size() const {
  return _internal_id_strings_size();
}
inline void PacketHeader::clear_id_strings() {
  _impl_.id_strings_.Clear();
}
inline ::ProtoMessage::PacketHeader_IdStringEntry* PacketHeader::mutable_id_strings(int index) {
  // @@protoc_insertion_point(field_mutable:ProtoMessage.PacketHeader.id_strings)
  return _impl_.id_strings_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ProtoMessage::PacketHeader_IdStringEntry >*
PacketHeader::mutable_id_strings() {
  // @@protoc_insertion_point(field_mutable_list:ProtoMessage.PacketHeader.id_strings)
  return &_impl_.id_strings_;
}
inline const ::ProtoMessage::PacketHeader_IdStringEntry& PacketHeader::_internal_id_strings(int index) const {
  return _impl_.id_strings_.Get(index);
}
inline const ::ProtoMessage::PacketHeader_IdStringEntry& PacketHeader::id_strings(int index) const {
  // @@protoc_insertion_point(field_get:ProtoMessage.PacketHeader.id_strings)
  return _internal_id_strings(index);
}
inline ::ProtoMessage::PacketHeader_IdStringEntry* PacketHeader::_internal_add_id_strings() {
  return _impl_.id_strings_.Add();
}
inline ::ProtoMessage::PacketHeader_IdStringEntry* PacketHeader::add_id_strings() {
  ::ProtoMessage::PacketHeader_IdStringEntry* _add = _internal_add_id_strings();
  // @@protoc_insertion_point(field_add:ProtoMessage.PacketHeader.id_strings)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ProtoMessage::PacketHeader_IdStringEntry >&
PacketHeader::id_strings() const {
  // @@protoc_insertion_point(field_list:ProtoMessage.PacketHeader.id_strings)
  return _impl_.id_strings_;
}

// -------------------------------------------------------------------

// Packet

// required uint64 tick = 1;
inline bool Packet::_internal_has_tick() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Packet::has_tick() const {
  return _internal_has_tick();
}
inline void Packet::clear_tick() {
  _impl_.tick_ = uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline uint64_t Packet::_internal_tick() const {
  return _impl_.tick_;
}
inline uint64_t Packet::tick() const {
  // @@protoc_insertion_point(field_get:ProtoMessage.Packet.tick)
  return _internal_tick();
}
inline void Packet::_internal_set_tick(uint64_t value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.tick_ = value;
}
inline void Packet::set_tick(uint64_t value) {
  _internal_set_tick(value);
  // @@protoc_insertion_point(field_set:ProtoMessage.Packet.tick)
}

// required uint32 cmd = 2;
inline bool Packet::_internal_has_cmd() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool Packet::has_cmd() const {
  return _internal_has_cmd();
}
inline void Packet::clear_cmd() {
  _impl_.cmd_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline uint32_t Packet::_internal_cmd() const {
  return _impl_.cmd_;
}
inline uint32_t Packet::cmd() const {
  // @@protoc_insertion_point(field_get:ProtoMessage.Packet.cmd)
  return _internal_cmd();
}
inline void Packet::_internal_set_cmd(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.cmd_ = value;
}
inline void Packet::set_cmd(uint32_t value) {
  _internal_set_cmd(value);
  // @@protoc_insertion_point(field_set:ProtoMessage.Packet.cmd)
}

// required uint64 addr = 3;
inline bool Packet::_internal_has_addr() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool Packet::has_addr() const {
  return _internal_has_addr();
}
inline void Packet::clear_addr() {
  _impl_.addr_ = uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline uint64_t Packet::_internal_addr() const {
  return _impl_.addr_;
}
inline uint64_t Packet::addr() const {
  // @@protoc_insertion_point(field_get:ProtoMessage.Packet.addr)
  return _internal_addr();
}
inline void Packet::_internal_set_addr(uint64_t value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.addr_ = value;
}
inline void Packet::set_addr(uint64_t value) {
  _internal_set_addr(value);
  // @@protoc_insertion_point(field_set:ProtoMessage.Packet.addr)
}

// required uint32 size = 4;
inline bool Packet::_internal_has_size() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool Packet::has_size() const {
  return _internal_has_size();
}
inline void Packet::clear_size() {
  _impl_.size_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline uint32_t Packet::_internal_size() const {
  return _impl_.size_;
}
inline uint32_t Packet::size() const {
  // @@protoc_insertion_point(field_get:ProtoMessage.Packet.size)
  return _internal_size();
}
inline void Packet::_internal_set_size(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.size_ = value;
}
inline void Packet::set_size(uint32_t value) {
  _internal_set_size(value);
  // @@protoc_insertion_point(field_set:ProtoMessage.Packet.size)
}

// optional uint32 flags = 5;
inline bool Packet::_internal_has_flags() const {
  bool value = (_impl_._has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline bool Packet::has_flags() const {
  return _internal_has_flags();
}
inline void Packet::clear_flags() {
  _impl_.flags_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000040u;
}
inline uint32_t Packet::_internal_flags() const {
  return _impl_.flags_;
}
inline uint32_t Packet::flags() const {
  // @@protoc_insertion_point(field_get:ProtoMessage.Packet.flags)
  return _internal_flags();
}
inline void Packet::_internal_set_flags(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000040u;
  _impl_.flags_ = value;
}
inline void Packet::set_flags(uint32_t value) {
  _internal_set_flags(value);
  // @@protoc_insertion_point(field_set:ProtoMessage.Packet.flags)
}

// optional uint64 pkt_id = 6;
inline bool Packet::_internal_has_pkt_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool Packet::has_pkt_id() const {
  return _internal_has_pkt_id();
}
inline void Packet::clear_pkt_id() {
  _impl_.pkt_id_ = uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline uint64_t Packet::_internal_pkt_id() const {
  return _impl_.pkt_id_;
}
inline uint64_t Packet::pkt_id() const {
  // @@protoc_insertion_point(field_get:ProtoMessage.Packet.pkt_id)
  return _internal_pkt_id();
}
inline void Packet::_internal_set_pkt_id(uint64_t value) {
  _impl_._has_bits_[0] |= 0x00000010u;
  _impl_.pkt_id_ = value;
}
inline void Packet::set_pkt_id(uint64_t value) {
  _internal_set_pkt_id(value);
  // @@protoc_insertion_point(field_set:ProtoMessage.Packet.pkt_id)
}

// optional uint64 pc = 7;
inline bool Packet::_internal_has_pc() const {
  bool value = (_impl_._has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool Packet::has_pc() const {
  return _internal_has_pc();
}
inline void Packet::clear_pc() {
  _impl_.pc_ = uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline uint64_t Packet::_internal_pc() const {
  return _impl_.pc_;
}
inline uint64_t Packet::pc() const {
  // @@protoc_insertion_point(field_get:ProtoMessage.Packet.pc)
  return _internal_pc();
}
inline void Packet::_internal_set_pc(uint64_t value) {
  _impl_._has_bits_[0] |= 0x00000020u;
  _impl_.pc_ = value;
}
inline void Packet::set_pc(uint64_t value) {
  _internal_set_pc(value);
  // @@protoc_insertion_point(field_set:ProtoMessage.Packet.pc)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace ProtoMessage

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_packet_2eproto
