// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trace.proto

#include "trace.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace ProtoMessage {
class traceRecordDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<traceRecord>
      _instance;
} _traceRecord_default_instance_;
}  // namespace ProtoMessage
namespace protobuf_trace_2eproto {
static void InitDefaultstraceRecord() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::ProtoMessage::_traceRecord_default_instance_;
    new (ptr) ::ProtoMessage::traceRecord();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ProtoMessage::traceRecord::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_traceRecord =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultstraceRecord}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_traceRecord.base);
}

::google::protobuf::Metadata file_level_metadata[1];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ProtoMessage::traceRecord, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ProtoMessage::traceRecord, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ProtoMessage::traceRecord, fetnumber_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ProtoMessage::traceRecord, addr_),
  0,
  ~0u,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, sizeof(::ProtoMessage::traceRecord)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::ProtoMessage::_traceRecord_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "trace.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\013trace.proto\022\014ProtoMessage\"N\n\013traceReco"
      "rd\022\021\n\tfetnumber\030\001 \002(\004\022\014\n\004addr\030\002 \003(\004\"\036\n\007a"
      "ddrCmd\022\010\n\004LOAD\020\000\022\t\n\005STORE\020\001"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 107);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "trace.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_trace_2eproto
namespace ProtoMessage {
const ::google::protobuf::EnumDescriptor* traceRecord_addrCmd_descriptor() {
  protobuf_trace_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_trace_2eproto::file_level_enum_descriptors[0];
}
bool traceRecord_addrCmd_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const traceRecord_addrCmd traceRecord::LOAD;
const traceRecord_addrCmd traceRecord::STORE;
const traceRecord_addrCmd traceRecord::addrCmd_MIN;
const traceRecord_addrCmd traceRecord::addrCmd_MAX;
const int traceRecord::addrCmd_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

// ===================================================================

void traceRecord::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int traceRecord::kFetnumberFieldNumber;
const int traceRecord::kAddrFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

traceRecord::traceRecord()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_trace_2eproto::scc_info_traceRecord.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:ProtoMessage.traceRecord)
}
traceRecord::traceRecord(const traceRecord& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      addr_(from.addr_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  fetnumber_ = from.fetnumber_;
  // @@protoc_insertion_point(copy_constructor:ProtoMessage.traceRecord)
}

void traceRecord::SharedCtor() {
  fetnumber_ = GOOGLE_ULONGLONG(0);
}

traceRecord::~traceRecord() {
  // @@protoc_insertion_point(destructor:ProtoMessage.traceRecord)
  SharedDtor();
}

void traceRecord::SharedDtor() {
}

void traceRecord::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* traceRecord::descriptor() {
  ::protobuf_trace_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_trace_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const traceRecord& traceRecord::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_trace_2eproto::scc_info_traceRecord.base);
  return *internal_default_instance();
}


void traceRecord::Clear() {
// @@protoc_insertion_point(message_clear_start:ProtoMessage.traceRecord)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  addr_.Clear();
  fetnumber_ = GOOGLE_ULONGLONG(0);
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool traceRecord::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ProtoMessage.traceRecord)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint64 fetnumber = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          set_has_fetnumber();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &fetnumber_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated uint64 addr = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 1, 16u, input, this->mutable_addr())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, this->mutable_addr())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ProtoMessage.traceRecord)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ProtoMessage.traceRecord)
  return false;
#undef DO_
}

void traceRecord::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ProtoMessage.traceRecord)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required uint64 fetnumber = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->fetnumber(), output);
  }

  // repeated uint64 addr = 2;
  for (int i = 0, n = this->addr_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(
      2, this->addr(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:ProtoMessage.traceRecord)
}

::google::protobuf::uint8* traceRecord::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:ProtoMessage.traceRecord)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required uint64 fetnumber = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->fetnumber(), target);
  }

  // repeated uint64 addr = 2;
  target = ::google::protobuf::internal::WireFormatLite::
    WriteUInt64ToArray(2, this->addr_, target);

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ProtoMessage.traceRecord)
  return target;
}

size_t traceRecord::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ProtoMessage.traceRecord)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // required uint64 fetnumber = 1;
  if (has_fetnumber()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->fetnumber());
  }
  // repeated uint64 addr = 2;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      UInt64Size(this->addr_);
    total_size += 1 *
                  ::google::protobuf::internal::FromIntSize(this->addr_size());
    total_size += data_size;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void traceRecord::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ProtoMessage.traceRecord)
  GOOGLE_DCHECK_NE(&from, this);
  const traceRecord* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const traceRecord>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ProtoMessage.traceRecord)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ProtoMessage.traceRecord)
    MergeFrom(*source);
  }
}

void traceRecord::MergeFrom(const traceRecord& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ProtoMessage.traceRecord)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  addr_.MergeFrom(from.addr_);
  if (from.has_fetnumber()) {
    set_fetnumber(from.fetnumber());
  }
}

void traceRecord::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ProtoMessage.traceRecord)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void traceRecord::CopyFrom(const traceRecord& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ProtoMessage.traceRecord)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool traceRecord::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  return true;
}

void traceRecord::Swap(traceRecord* other) {
  if (other == this) return;
  InternalSwap(other);
}
void traceRecord::InternalSwap(traceRecord* other) {
  using std::swap;
  addr_.InternalSwap(&other->addr_);
  swap(fetnumber_, other->fetnumber_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata traceRecord::GetMetadata() const {
  protobuf_trace_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_trace_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace ProtoMessage
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::ProtoMessage::traceRecord* Arena::CreateMaybeMessage< ::ProtoMessage::traceRecord >(Arena* arena) {
  return Arena::CreateInternal< ::ProtoMessage::traceRecord >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
