#
# Copyright (C) 2012-2020 Intel Corporation.
# SPDX-License-Identifier: MIT
#

##############################################################
#
# This file includes all the test targets as well as all the
# non-default build rules and test recipes.
#
##############################################################


##############################################################
#
# Test targets
#
##############################################################

###### Place all generic definitions here ######

# This defines tests which run tools of the same name.  This is simply for convenience to avoid
# defining the test name twice (once in TOOL_ROOTS and again in TEST_ROOTS).
# Tests defined here should not be defined in TOOL_ROOTS and TEST_ROOTS.
TEST_TOOL_ROOTS :=  #MyPinTool testMem testOp testPid testOp2 tracer tracerWithSyscall

# This defines the tests to be run that were not already defined in TEST_TOOL_ROOTS.
TEST_ROOTS := 

# This defines the tools which will be run during the the tests, and were not already defined in
# TEST_TOOL_ROOTS.
TOOL_ROOTS := 

# This defines the static analysis tools which will be run during the the tests. They should not
# be defined in TEST_TOOL_ROOTS. If a test with the same name exists, it should be defined in
# TEST_ROOTS.
# Note: Static analysis tools are in fact executables linked with the Pin Static Analysis Library.
# This library provides a subset of the Pin APIs which allows the tool to perform static analysis
# of an application or dll. Pin itself is not used when this tool runs.
SA_TOOL_ROOTS :=

# This defines all the applications that will be run during the tests.
APP_ROOTS :=

# This defines any additional object files that need to be compiled.
OBJECT_ROOTS := 

# This defines any additional dlls (shared objects), other than the pintools, that need to be compiled.
DLL_ROOTS := 

# This defines any static libraries (archives), that need to be built.
LIB_ROOTS := 

###### Handle exceptions here (OS/arch related) ######

RUNNABLE_TESTS := $(TEST_TOOL_ROOTS) $(TEST_ROOTS)

###### Handle exceptions here (bugs related) ######

###### Define the sanity subset ######

# This defines the list of tests that should run in sanity. It should include all the tests listed in
# TEST_TOOL_ROOTS and TEST_ROOTS excluding only unstable tests.
SANITY_SUBSET := $(TEST_TOOL_ROOTS) $(TEST_ROOTS)


##############################################################
#
# Test recipes
#
##############################################################

# This section contains recipes for tests other than the default.
# See makefile.default.rules for the default test rules.
# All tests in this section should adhere to the naming convention: <testname>.test


##############################################################
#
# Build rules
#
##############################################################
# Build the intermediate object file.


# INCS += -I/usr/local/include/google/protobuf
# LPATHS += -L/usr/local/lib -Wl, -rpath,/usr/local/lib
# LIBS += -lprotobuf -pthread
# TOOL_LPATHS += -L/usr/local/lib -Wl,-rpath,/usr/local/lib
# TOOL_LIBS += -lrt -lprotobuf



# TOOL_CXXFLAGS += -DUSING_PIN -I$(HOME)/opt/libtrace/include

# $(OBJDIR)Source1$(OBJ_SUFFIX): trace.pb.cc
# 	$(CXX) $(TOOL_CXXFLAGS) $(COMP_OBJ)$@ $<

# $(OBJDIR)Source2$(OBJ_SUFFIX): protoio.cc
# 	$(CXX) $(TOOL_CXXFLAGS) $(COMP_OBJ)$@ $<

# $(OBJDIR)Source3$(OBJ_SUFFIX): tracerProto.cpp
# 	$(CXX) $(TOOL_CXXFLAGS)   $(COMP_OBJ)$@ $<

# # Build the tool as a dll (shared object).
# $(OBJDIR)tracerProto2$(PINTOOL_SUFFIX): $(OBJDIR)Source1$(OBJ_SUFFIX)  $(OBJDIR)Source2$(OBJ_SUFFIX)  $(OBJDIR)Source3$(OBJ_SUFFIX)
# 	echo "$(TOOL_LPATHS) ddddddsfdfdfdfdfdfdfdfdfdfdfdfdf"
# 	echo $(CXX -v) 
# 	$(LINKER) $(TOOL_LDFLAGS)  $(LINK_EXE)$@ $(^:%.h=) $(TOOL_LPATHS) $(TOOL_LIBS)

# This section contains the build rules for all binaries that have special build rules.
# See makefile.default.rules for the default build rules.
dddd :
	@echo "$(OBJDIR)"tracer2"$(PINTOOL_SUFFIX)"

$(OBJDIR)tracer$(OBJ_SUFFIX): tracer.cpp
	$(CXX) $(TOOL_CXXFLAGS) $(COMP_OBJ)$@ $<

$(OBJDIR)tracer2$(PINTOOL_SUFFIX): $(OBJDIR)tracer$(OBJ_SUFFIX)
	$(LINKER) $(TOOL_LDFLAGS_NOOPT) $(LINK_EXE)$@ $(^:%.h=) $(TOOL_LPATHS) $(TOOL_LIBS)
